name: flexi_cart_updater
description: A package for manage cart icon all over the app
version: 1.0.5
homepage: https://github.com/Dharini17/flexi_cart_updater

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Preview of cart'
    path: screenshots/screenshot1.png
